### ISSUE TITLE
最近在看Kotlin，想交个朋友共同学习。

### ISSUE THREAD

**Issue by guoyibin27** [nekocode/create-android-kotlin-app#2]

**Comment by nekocode** [comment]
@guoyibin27 :smile: OK 喔，共同学习~

**Comment by GodJobs** [comment]
建个群，或者slack群组啊

**Comment by nekocode** [comment]
Check this out: [![Join the chat at https://gitter.im/nekocode/kotlin_android_base_framework](https://badges.gitter.im/nekocode/kotlin_android_base_framework.svg)](https://gitter.im/nekocode/kotlin_android_base_framework?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Or join this QQ Group: 243388300

**Comment by JackRo** [comment]
I also learn kotlin recently. I want to join you!

**Comment by fastZhang** [comment]
一起学习

**Comment by charleshaye** [comment]
no stop i trying to work/jk
